#!/bin/bash

print_usage () {
  cat << EOM
Usage: $0
    List nodes with down GPUs.

Arguments:
    None.

Output:
    Lists each node with at least one down GPU on separate lines.

EOM
}

if [ ${#@} -gt 0 ]; then
    print_usage
    exit
fi

relative_dir=`dirname $0`
down_gpus=''
full_capacity=`${relative_dir}/gpu-usage -h | awk -F',' '{if ($2 == $3) printf("true"); else printf("false")}'`
down_gpus=`${relative_dir}/gpu-usage-by-node -p | awk 'NR==1 {print $0} NR > 1 {if ($6 > $5) print $0}'`
if $full_capacity; then
  echo 'All up!'
else
  echo "${down_gpus}"
  echo ""
  echo "Full cluster status:"
  ${relative_dir}/cluster-status
fi
