#!/bin/bash
relative_dir=`dirname $0`
down_gpus=''
full_capacity=`${relative_dir}/gpu-usage -h | awk -F',' '{if ($2 == $3) printf("true"); else printf("false")}'`
down_gpus=`${relative_dir}/gpu-usage-by-node -p | awk 'NR==1 {print $0} NR > 1 {if ($6 > $5) print $0}'`
if $full_capacity; then
  echo 'All up!'
else
  echo "${down_gpus}"
  echo ""
  echo "Full cluster status:"
  ${relative_dir}/cluster-status
fi
