#!/bin/bash
relative_dir=`dirname $0`
full_capacity=`${relative_dir}/gpu-usage -h | awk -F',' '{if ($1 == $2) printf("true"); else printf("false")}'`
free_gpus=`${relative_dir}/gpu-usage-by-node -p | awk 'NR==1 {print $0} NR > 1 {if ($5 > $4) print $0}'`
if $full_capacity; then
  echo No gpus free...join the squeue!
  echo "Tip: you can use the command sprio to observe your job's priority"
  echo "Current queue:"
  sprio -l
else
  echo "${free_gpus}"
fi
