#!/bin/bash

default_args="--partition=Interactive --time=02:00:00 --mem=14000 --cpus-per-task=4"
read -r -d '' default_msg << EOM
======================= WELCOME MESSAGE =======================
It's good practice to set a few parameters when using srun
(this command is essentailly an alias for 'srun --pty bash').
We have added some default parameters to maximise your chance
of getting an interactive session. See the Slurm Documentation
for further info.

https://slurm.schedmd.com/

Default args added:
[$default_args]

Useful arg examples:
* --time=08:00:00        terminate job after 8 hours (good
                         practice and curteous)
* --time=1-04:00:30      terminate job after 1 day, 4 hours,
                         and 30 seconds
* --gres=gpu:1           give me 1 gpu
* --nodelist=charles19   put me on a specific node
* --mem=4000             give me 4G of RAM, there's about 50G
                         per box but memory is not shared 
                         (note this is not GPU memory)
* --cpus-per-task=1      give me 1 cpu, there's 32 on most
                         nodes
* --partition=...        there is a partition explicitly for
                         interactive jobs (called Partition).
                         You are welcome to run interactive
                         jobs on other partitions if the
                         Interactive partition is full. To
                         get the full list, run "sinfo"

For more informtion about node configuration, see the
computing support docs:
http://computing.help.inf.ed.ac.uk/james-and-charles-cluster


When you run this command with args, this message will
disappear, and no additional args will be added.
===============================================================
EOM

print_usage () {
  cat << EOM
Usage: $0 [other args for srun] 

Arguments:
    see documentation for srun. You can specify all arguments, and they'll
    be used.
EOM
}

if [ $# -eq 0 ]; then
    echo "$default_msg"
    args=$default_args
else
    args=$@
fi

echo
echo Doing a --test-only to estimate wait time...
srun $args --test-only --pty bash
echo

echo Running the following command to get you an interactive session:
echo "srun $args --pty bash"
echo ...
srun $args --pty bash
