#!/bin/bash

nodes=`sinfo --format="%N" --noheader`

print_usage () {
  cat << EOM
Runs given script on all nodes by submitting supplied script with sbatch

Usage: $0 [-n nodelist] script 
Arguments:
script    the script to be submitted to slurm via sbatch
    -n    (optional) specify nodes, either comma separated list, or summarised.
          Mirrors slurm command -n usage in sinfo, and -w usage for squeue." 
EOM
}

while getopts 'n:' flag; do
  case "${flag}" in
    n) nodes="${OPTARG}" ;;
    *) print_usage
       exit 1 ;;
  esac
done

script="${@:$OPTIND:1}"
if [ "$script" = "" ]; then
    >&2 echo "You must supply a script"
    exit 1
fi

node_partition_list=`sinfo --format="%n,%R" --noheader -n ${nodes} -N`
node=`echo "${node_partition_list}" | cut -f1 -d','` 
partition=`echo "${node_partition_list}" | cut -f2 -d','` 
parallel --link "sbatch --partition={1} --nodelist={2} ${script}" ::: $partition ::: $node 

