#! /bin/bash

if [ $# -eq 0 ] || [ "$1" == "help" ] ; then
  echo "Usage: $0 JOB_ID [LESS_ARGS]"
  echo "    Runs less on the output file of a running job."
  echo "Arguments:"
  echo "    JOB_ID: (Required) Job to get output file for." 
  echo "            Can be either a job number or a string to match a job name."
  echo "    [LESS_ARGS]: (Optional) Any arguments to be passed through to the less command."
  exit
fi

out_path=`get-output-file "$1"`
if [ ! $? -eq 0 ] ; then
    echo $out_path
    exit $?
fi
shift
#echo "$out_path"
less "${@}" $out_path
