#! /bin/bash

if [ $# -ne 1 ] || [ "$1" == "help" ] ; then
  echo "Usage: $0 JOB_ID [TAIL_ARGS]"
  echo "    Runs tail on the output file of a running job."
  echo "    If the file does not yet exist, will wait for it to be created."
  echo "    Runs with the '-f' option on tail, so as output is written to the file,"
  echo "      it will be printed to the screen."
  echo "Arguments:"
  echo "    JOB_ID: (Required) Job to get output file for." 
  echo "            Can be either a job number or a string to match a job name."
  echo "    [TAIL_ARGS]: (Optional) Any arguments to be passed through to the tail command."
  exit
fi

# Get the path for the output file
out_path=`get-output-file "$1"`

if [ ! $? -eq 0 ] ; then
    echo $out_path
    exit $?
fi
shift

# Wait for the file to exist
until [ -e "$out_path" ]; do
    sleep 5s
done

tail "${@}" -f $out_path
