#! /bin/bash

if [ $# -ne 1 ] || [ "$1" == "help" ] ; then
  echo "Usage: $0 FOLDER_NAME"
  echo "   Executes watch tail on the most recently created file in a folder"
  echo "   Intended to be used with a log folder as the argument to watch the"
  echo "   most recent job kicked off" 
  echo "Arguments:"
  echo "    FOLDER_NAME: (Required) Folder to get the most recent file from" 
  exit
fi

ntail=20
filename=`ls -t "$1"/* | head -1`
watch tail -$ntail $filename

