#! /bin/bash

if [ $# -ne 1 ] || [ "$1" == "help" ] ; then
  echo "Usage: $0 FOLDER_NAME"
  echo "   Executes less on the most recently created file in a folder"
  echo "   Intended to be used with a log folder as the argument to less the"
  echo "   most recent job kicked off. TIP: type G in less to go to bottom." 
  echo "Arguments:"
  echo "    FOLDER_NAME: (Required) Folder to get the most recent file from" 
  exit
fi

ntail=20
filename=`ls -t "$1"/* | head -1`
less -R $filename

