#! /bin/bash
if [ $# -ne 1 ] || [ "$1" == "help" ] ; then
  echo "Usage: $0 JOB_ID"
  echo "    Cats the output file of a running job."
  echo "Arguments:"
  echo "    JOB_ID: (Required) Job to get output file for." 
  echo "            Can be either a job number or a string to match a job name."
  exit
fi
out_path=`get-output-file "$1"`
if [ ! $? -eq 0 ] ; then
    echo $out_path
    exit $?
fi
cat $out_path
