#! /bin/bash

if [ "$1" == "help" ] ; then
  echo "Usage: $0 [QSTATUS_ARGS]" 
  echo "    Appends the names of job owners to the output of qstatus."
  echo "Arguments:"
  echo "    QSTATUS_ARGS: (Optional) arguments that modify the output of qstatus."
  echo "                  See 'man qstatus' for a full list."
  exit
fi

# Pass arguments through to qstatus
QSTATUS_OUT=`qstatus "$@"`

# Find out if the owner column is present:
echo "$QSTATUS_OUT" | grep "owner" &> /dev/null

# (If grep finds a match, it will return with an exit code of 0, otherwise 1.
# "#?" stores the exit code of the last command, so can condition on the value of this.)

if [ $? -eq 0 ] ; then
    # If the owner column is present, look up the names of the owners.
    echo "$QSTATUS_OUT" | awk -F '[[:space:]]+' '{if (NR <= 3 || NF == 0 || substr ($0 , 0, 10) == "Waiting jo" || substr ($0, 0, 10) == " job-ID  #" || substr ($0, 0, 10) == "----------") print $0; else  {printf("%7s %2d %-25s ",$2,$3,$4); system("finger " $5" | head -1 | cut -f 4- | cut -d ':' -f 2- | tr -d '\''\n'\''" );printf(" %-10s %s %s\n", $6, $7, $8)} }'
    #echo "$QSTATUS_OUT" | awk -F '[[:space:]]+' -v nlines=$(echo "$QSTATUS_OUT" | wc -l) '{if (NR <= 3) print $0; else if (NR < nlines) {printf("%-85s",$0); system("finger " $5" | head -1 | cut -f 4-" )} }'  
else
    # Otherwise, just display the output of qstatus
    echo "$QSTATUS_OUT"
fi
