#!/bin/bash

# Looks up the finished jobs of the current user from the  last DAYS days (default 7)
# and prints the number, name and submission time.


# Colour codes for failed/succeeded jobs.
# Uses bash colour codes.
FAILED_CC="1;31"
SUCCEEDED_CC="1;32"

#if [[ "$1" == "help" ]] ; then
print_help() {
    echo "Usage: show-past-jobs [-e] [-d DAYS] [-u USER] [-V|--verbose] [--filter 'COL=EXP,...'] [-h|--help]"
    echo "    [-e]  : (Optional) select jobs by end time rather than start time."
    echo "    [-d DAYS]: (Optional) Integer defining how many days back to look."
    echo "            Defaults to 7."
    echo "    [-u USER]: (Optional) Requires an argument for DAYS. Defaults to current user."
    echo "    [-V|--verbose]: (Optional) Verbose. Does not shorten job names."
    echo "    [--filter COL=EXP,...]: (Optional) Only show jobs that match expression EXP in column COL."
    echo "                          Multiple criteria should be seperated by commas."
    echo "                          Valid column names are:"
    echo "                              'id' -- Job # "
    echo "                              'task' -- Task "
    echo "                              'name' -- Name "
    echo "                              'exit' -- Exit Status "
    echo "                              'host' -- Host "
    echo "                          The expression EXP should be an awk regular expression."
    echo "    [-h|--help]: Print this message."
}

N_DAYS=7
LOOKUP_USER="$USER"

while :
do
    case "$1" in 
      -d)
        N_DAYS=$2
        shift 2
        ;;
      -u)
        LOOKUP_USER="$2"
        shift 2
        ;;
      -e)
        END_TIME="True"
        shift
        ;;
      -V)
        VERBOSE="True"
        shift
        ;;
      --verbose)
	VERBOSE="TRUE"
	shift
	;;
      --filter)
        filter_func="$2"
        shift 2
        ;;
      --help)
	print_help
	exit
	;;
      help)
	print_help
	exit
	;;
      -h)
	print_help
	exit
	;;
      *)
        break
        ;;
    esac
done

make_filter() {
    # Change names into column numbers:
    filters="$1"
    filters="${filters//id=/\$1=}"
    filters="${filters//task=/\$2=}"
    filters="${filters//name=/\$3=}"
    filters="${filters//exit=/\$4=}"
    filters="${filters//host=/\$5=}"
    filters="${filters//=/~/}"
    filters="${filters//,// && }/"
#'BEGIN{ FPAT = "([[:space:]]*[^[:space:]]+)";OFS=""}
   # OUT=$(echo  "$1" | awk -v filters="$filters" "$filters") #{if (filters) {print}}')
}

convert_from_seconds() {
    # Converts number of seconds to useful format
    SECONDS=$1
    DAYS=$(($SECONDS / 86400))
    SECONDS=$(($SECONDS - $DAYS * 86400))
    HOURS=$(($SECONDS / 3600))
    SECONDS=$(($SECONDS - $HOURS * 3600))
    MINUTES=$(($SECONDS / 60))
    SECONDS=$(($SECONDS - $MINUTES * 60))
    DURATION=`printf "%02d:%02d:%02d:%02d" $DAYS $HOURS $MINUTES $SECONDS`
#    DURATION=''
#    if [[ $DAYS -gt 0 ]] ; then DURATION="$DURATION${DAYS}d "; fi
#    if [[ $HOURS -gt 0 ]] ; then DURATION="$DURATION${HOURS}h "; fi
#    if [[ $MINUTES -gt 0 ]] ; then DURATION="$DURATION${MINUTES}m "; fi
#    DURATION="$DURATION${SECONDS}s"
}

# Look up the target jobs and pull out the desired info
if [[ ! -z "$END_TIME" ]] ; then
    PAST_JOBS=`qacct -u "$LOOKUP_USER" -j -E -d "$N_DAYS"`    
else
    PAST_JOBS=`qacct -u "$LOOKUP_USER" -j -d "$N_DAYS"`
fi
NAMES=(`echo "$PAST_JOBS" | grep "^jobname" | awk '{print $2}'`)
NUMBERS=(`echo "$PAST_JOBS" | grep "^jobnumber" | awk '{print $2}'`)
TASKIDS=(`echo "$PAST_JOBS" | grep "^taskid" | awk '{print $2}'`)
OLD_IFS=$IFS
IFS=$'\n'
QSUB_TIMES=(`echo "$PAST_JOBS" | grep "^qsub_time" | cut -d ' ' -f 2- | awk '{print $2 " " $3 " " $4 }'`)
START_TIMES=(`echo "$PAST_JOBS" | grep "^start_time" | cut -d ' ' -f 2-`)
END_TIMES=(`echo "$PAST_JOBS" | grep "^end_time" | cut -d ' ' -f 2-`)
EXIT_STATUSES=(`echo "$PAST_JOBS" | grep "^exit_status" | cut -d ' ' -f 2-`)    
IFS=$OLD_IFS
HOSTNAMES=(`echo "$PAST_JOBS" | grep "^hostname" |  awk '{print $2}'`)
exit_filter=0
if [[ $filter_func =~ .*exit.* ]] ; then
    exit_filter=1
fi

# Loop through extracted info and format it for printing
OUT=''
HEADER="Showing past jobs for user ${LOOKUP_USER}:\nJob # \tTask    Name  \t\t    Exit Status  Host \t\tDuration \t Sub Time"
for i in `seq 0	"$((${#NAMES[@]}-1))"`;	do
        # Colour code the exit status:
        EXIT_STATUS=`echo "${EXIT_STATUSES[$i]}" | tr -d '[:space:]' | head -c 3`
        if [[ "$EXIT_STATUS" == "0" ]] && [[ $exit_filter -ne 1 ]] ; then EXIT_STATUS="\e[${SUCCEEDED_CC}m$EXIT_STATUS\e[m"; fi
        if [[ "$EXIT_STATUS" == "1" ]] && [[ $exit_filter -ne 1 ]] ; then EXIT_STATUS="\e[${FAILED_CC}m$EXIT_STATUS\e[m"; fi
        # If an array job, get the taskid:
        if [[ "${TASKIDS[$i]}" == "undefined" ]] ; then TASK_ID="-"; else TASK_ID="${TASKIDS[$i]}"; fi
        # Extract the first section of the hostname:
        HOSTNAME=(${HOSTNAMES[$i]//./ })
        # Change the duration to a useful format:
        convert_from_seconds $((`date --date="${END_TIMES[$i]}" +%s` - `date --date="${START_TIMES[$i]}" +%s`))
        # Limit the length of the name to 20 characters:
        NAME=${NAMES[$i]}
        if [[ ${#NAME} -gt 20 ]] && [[ -z "$VERBOSE" ]] ; then NAME="${NAME:0:7}...${NAME: -7}"; fi
        if [[ ${#NAME} -lt 8 ]] ; then NAME="${NAME}\t"; fi
        if [[ ${#NAME} -lt 16 ]] ; then NAME="${NAME}\t"; fi
        if [[ ${#DURATION} -lt 8 ]] ; then DURATION="${DURATION}\t" ; fi
        if [[ ${#DURATION} -lt 16 ]] ; then DURATION="${DURATION}\t" ; fi
        OUT="$OUT\n${NUMBERS[$i]}\t${TASK_ID}\t${NAME}\t${EXIT_STATUS}\t${HOSTNAME[0]}\t${DURATION}${QSUB_TIMES[$i]}" 
done

# Output everything sorted by job number:
echo -e "$HEADER"
echo "--------------------------------------------------------------------------------------------------"
if [[ -n "$filter_func" ]] ; then
    make_filter "$filter_func"
    echo -e	$OUT | sort -k 1,1nr -k 2,2n | awk "$filters"
else
    echo -e	$OUT | sort -k 1,1nr -k 2,2n
fi
